name: ChatGPTForMinecraft
version: '${project.version}'
main: net.kanade1825.litematica.chatgptforminecraft.ChatGPTForMinecraft
api-version: 1.19
commands:
  chatgpt-setup:
    description: Set up command
  sendtalkfile:
    description: send talk file
  gettalkfile:
    description: access chatgpt for minecraft server
  chatgpt:
    description: chatgpt wo nihonngode tukaeruyounisuru komanndo